### ISSUE TITLE
404 Page Not Found

### ISSUE THREAD

**Issue by mvpopuk** [laravelcm/website#5]
Hi, thanks for publishing the source of this website. I love it and I want to do something similar for the Romanian Laravel Community. I cloned the repo, followed the instructions, I did migrated the db but when I try to access the website in browser, I get a 404 Page Not Found. I wonder what I did wrong. Thanks.

**Comment by mckenziearts** [comment]
The current source code will be release this night

**Comment by mckenziearts** [comment]
@mvpopuk source code is available

**Comment by mvpopuk** [comment]
Do you have only the html / css ? I'd be interested to rebuild the website using laravel and vue. Thanks very much.
